// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKIddnmmtbT8-cxIoTi-0YGS_Q9ou4iPE',
    appId: '1:329150979920:web:ce9c7bf23011c8f4199655',
    messagingSenderId: '329150979920',
    projectId: 'uclan-beauty-ai-app',
    authDomain: 'uclan-beauty-ai-app.firebaseapp.com',
    storageBucket: 'uclan-beauty-ai-app.firebasestorage.app',
    measurementId: 'G-SB4086TJTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCvLdSMsEEu3sZma8XhiRDz4q-LXL-icw',
    appId: '1:329150979920:android:73a5e2fc2a21a642199655',
    messagingSenderId: '329150979920',
    projectId: 'uclan-beauty-ai-app',
    storageBucket: 'uclan-beauty-ai-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85m7KgBb_UUZg2R9KBpcrJ91GwJ7uTHg',
    appId: '1:329150979920:ios:79127f7a142ebe4c199655',
    messagingSenderId: '329150979920',
    projectId: 'uclan-beauty-ai-app',
    storageBucket: 'uclan-beauty-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.beautyAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85m7KgBb_UUZg2R9KBpcrJ91GwJ7uTHg',
    appId: '1:329150979920:ios:79127f7a142ebe4c199655',
    messagingSenderId: '329150979920',
    projectId: 'uclan-beauty-ai-app',
    storageBucket: 'uclan-beauty-ai-app.firebasestorage.app',
    iosBundleId: 'com.example.beautyAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKIddnmmtbT8-cxIoTi-0YGS_Q9ou4iPE',
    appId: '1:329150979920:web:1a4dda37a6139b95199655',
    messagingSenderId: '329150979920',
    projectId: 'uclan-beauty-ai-app',
    authDomain: 'uclan-beauty-ai-app.firebaseapp.com',
    storageBucket: 'uclan-beauty-ai-app.firebasestorage.app',
    measurementId: 'G-5YBGN5M263',
  );
}
